In [4]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
from prepare_LIAS import process_all_LIAS_files
from tsfresh_features_LIAS import extract_tsfresh_features



In [6]:
WINDOW_SIZE = 1024
OVERLAP = int(WINDOW_SIZE/2)

# Call the new function to process all files
all_processed_windows_a, all_processed_windows_b, all_processed_windows_c = process_all_LIAS_files(WINDOW_SIZE, OVERLAP)

print(f"Total processed windows for 'isa': {len(all_processed_windows_a)}")
print(f"Total processed windows for 'isb': {len(all_processed_windows_b)}")
print(f"Total processed windows for 'isc': {len(all_processed_windows_c)}")

Found 162 files: ['ccs0.csv', 'ccs1.csv', 'ccs10.csv', 'ccs100.csv', 'ccs101.csv', 'ccs102.csv', 'ccs103.csv', 'ccs104.csv', 'ccs105.csv', 'ccs106.csv', 'ccs107.csv', 'ccs108.csv', 'ccs109.csv', 'ccs11.csv', 'ccs110.csv', 'ccs111.csv', 'ccs112.csv', 'ccs113.csv', 'ccs114.csv', 'ccs115.csv', 'ccs116.csv', 'ccs117.csv', 'ccs12.csv', 'ccs120.csv', 'ccs121.csv', 'ccs122.csv', 'ccs123.csv', 'ccs124.csv', 'ccs125.csv', 'ccs126.csv', 'ccs127.csv', 'ccs128.csv', 'ccs129.csv', 'ccs13.csv', 'ccs130.csv', 'ccs131.csv', 'ccs132.csv', 'ccs133.csv', 'ccs134.csv', 'ccs135.csv', 'ccs136.csv', 'ccs137.csv', 'ccs14.csv', 'ccs140.csv', 'ccs141.csv', 'ccs142.csv', 'ccs143.csv', 'ccs144.csv', 'ccs145.csv', 'ccs146.csv', 'ccs147.csv', 'ccs148.csv', 'ccs149.csv', 'ccs15.csv', 'ccs150.csv', 'ccs151.csv', 'ccs152.csv', 'ccs153.csv', 'ccs154.csv', 'ccs155.csv', 'ccs156.csv', 'ccs157.csv', 'ccs16.csv', 'ccs160.csv', 'ccs161.csv', 'ccs162.csv', 'ccs163.csv', 'ccs164.csv', 'ccs165.csv', 'ccs166.csv', 'ccs167.csv',

Processing files:   0%|          | 0/162 [00:00<?, ?it/s]

Processing files: 100%|██████████| 162/162 [00:02<00:00, 56.06it/s]

Total processed windows for 'isa': 4050
Total processed windows for 'isb': 4050
Total processed windows for 'isc': 4050


In [7]:
all_processed_windows_a[0]

{'data': [2.7295,
  1.53565,
  0.380857,
  -1.115745,
  -2.3706,
  -2.9760999999999997,
  -3.2886,
  -2.8345000000000002,
  -1.68945,
  -0.541995,
  0.9179550000000001,
  2.2876,
  2.91505,
  3.2983000000000002,
  2.9663,
  1.8994499999999999,
  0.717775,
  -0.65186,
  -2.09965,
  -2.8174,
  -3.23,
  -3.0518,
  -2.03125,
  -0.8642449999999999,
  0.4541025,
  1.9458,
  2.77095,
  3.22265,
  3.15915,
  2.23875,
  1.04246,
  -0.20751999999999998,
  -1.7749,
  -2.6709,
  -3.1714,
  -3.2007,
  -2.3877,
  -1.174305,
  0.03906000000000001,
  1.58935,
  2.6123,
  3.12255,
  3.2788500000000003,
  2.56595,
  1.3794,
  0.18555,
  -1.3257,
  -2.49265,
  -3.03225,
  -3.26905,
  -2.6904500000000002,
  -1.499,
  -0.35400600000000004,
  1.137705,
  2.3876999999999997,
  2.98095,
  3.28855,
  2.85155,
  1.7089499999999997,
  0.55664,
  -0.883765,
  -2.25585,
  -2.8955,
  -3.29105,
  -2.9467499999999998,
  -1.875,
  -0.6909150000000001,
  0.690925,
  2.1411,
  2.854,
  3.26175,
  3.07865,
  2.05565,
  0

In [8]:
def windows_to_dataframe(processed_windows):
    rows = []

    for window in processed_windows:
        row = window["metadata"].copy()

        for i, value in enumerate(window["data"]):
            row[f"sample_{i}"] = value

        rows.append(row)

    return pd.DataFrame(rows)

In [9]:
# Step 2: Convert windows to DataFrames

df_a = windows_to_dataframe(all_processed_windows_a)

df_b = windows_to_dataframe(all_processed_windows_b)

df_c = windows_to_dataframe(all_processed_windows_c)

In [10]:
df_a

,file_name,window_num,window_size,overlap,signal_type,sample_0,sample_1,sample_2,sample_3,sample_4,...,sample_502,sample_503,sample_504,sample_505,sample_506,sample_507,sample_508,sample_509,sample_510,sample_511
0,ccs0.csv,0,1024,512,isa,2.729500,1.535650,0.380857,-1.115745,-2.370600,...,0.380862,-1.101070,-2.373050,-2.971200,-3.286150,-2.841800,-1.69190,-0.541990,0.905775,2.26560
1,ccs0.csv,1,1024,512,isa,3.288600,2.849150,1.689450,0.559085,-0.881350,...,1.716300,0.546875,-0.881325,-2.236350,-2.890650,-3.256850,-2.95655,-1.855450,-0.717795,0.66162
2,ccs0.csv,2,1024,512,isa,2.929700,3.305650,2.993150,1.892100,0.732420,...,2.985850,1.899400,0.727550,-0.656755,-2.084950,-2.834450,-3.25195,-3.068850,-2.043500,-0.87156
3,ccs0.csv,3,1024,512,isa,2.119100,2.836900,3.264150,3.066400,2.075200,...,3.251950,3.090800,2.067900,0.910640,-0.397951,-1.911600,-2.74170,-3.203100,-3.142100,-2.23145
4,ccs0.csv,4,1024,512,isa,0.439452,1.975100,2.766100,3.237300,3.159200,...,2.780750,3.229950,3.188500,2.263200,1.064475,-0.173340,-1.73095,-2.651400,-3.156750,-3.20555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4045,ccs97.csv,20,1024,512,isa,1.931150,2.475600,2.585450,1.940950,1.142555,...,2.697750,2.080100,1.279300,0.397946,-0.932635,-1.752950,-2.31200,-2.666000,-2.163050,-1.38425
4046,ccs97.csv,21,1024,512,isa,1.096190,1.843250,2.414550,2.687950,2.128950,...,2.331550,2.648900,2.172850,1.386700,0.571285,-0.786125,-1.71140,-2.280250,-2.687950,-2.30225
4047,ccs97.csv,22,1024,512,isa,-0.517575,0.800775,1.713850,2.258300,2.680650,...,1.616200,2.192350,2.607450,2.299850,1.481950,0.700685,-0.54199,-1.555200,-2.094750,-2.57325
4048,ccs97.csv,23,1024,512,isa,-1.477050,-0.720215,0.581055,1.608850,2.175300,...,0.527340,1.594250,2.116700,2.609900,2.419400,1.616200,0.90576,-0.258790,-1.442900,-2.01415


In [30]:
# Step 3: Extract TSFresh features

df_features_a = extract_tsfresh_features(df_a, "ISA")
df_features_b = extract_tsfresh_features(df_b, "ISB")
df_features_c = extract_tsfresh_features(df_c, "ISC")

Extracting TSFresh features for ISA...


Feature Extraction: 100%|██████████| 4050/4050 [00:02<00:00, 1383.10it/s]


Finished feature extraction for ISA. Shape: (4050, 49)
Extracting TSFresh features for ISB...


Feature Extraction: 100%|██████████| 4050/4050 [00:02<00:00, 1466.79it/s]


Finished feature extraction for ISB. Shape: (4050, 49)
Extracting TSFresh features for ISC...


Feature Extraction: 100%|██████████| 4050/4050 [00:02<00:00, 1504.53it/s]


Finished feature extraction for ISC. Shape: (4050, 49)


In [31]:
df_features_a

,file_name,window_num,window_size,overlap,signal_type,value__sum_values,value__median,value__mean,value__length,value__standard_deviation,...,value__energy_ratio_by_chunks__num_segments_10__segment_focus_3,value__energy_ratio_by_chunks__num_segments_10__segment_focus_4,value__energy_ratio_by_chunks__num_segments_10__segment_focus_5,value__energy_ratio_by_chunks__num_segments_10__segment_focus_6,value__energy_ratio_by_chunks__num_segments_10__segment_focus_7,value__energy_ratio_by_chunks__num_segments_10__segment_focus_8,value__energy_ratio_by_chunks__num_segments_10__segment_focus_9,"value__fft_aggregated__aggtype_""centroid""","value__fft_aggregated__aggtype_""variance""",value__permutation_entropy__dimension_8__tau_1
0,ccs0.csv,0,1024,512,isa,-1.237287,0.006100,-0.002417,512.0,2.301300,...,0.101323,0.101909,0.100975,0.099336,0.098091,0.098492,0.099865,44.531847,1359.664937,3.726162
1,ccs0.csv,1,1024,512,isa,0.146755,0.006102,0.000287,512.0,2.304617,...,0.099752,0.100891,0.101756,0.100928,0.098892,0.098178,0.097782,50.569366,1915.515404,3.725282
2,ccs0.csv,2,1024,512,isa,2.883274,0.006105,0.005631,512.0,2.308459,...,0.097817,0.098952,0.100346,0.101478,0.100874,0.099057,0.097575,57.884691,2630.521291,3.723227
3,ccs0.csv,3,1024,512,isa,6.352560,0.008545,0.012407,512.0,2.310324,...,0.097653,0.097192,0.098835,0.099970,0.101012,0.101001,0.098956,59.580490,2656.316965,3.723227
4,ccs0.csv,4,1024,512,isa,9.804839,0.013427,0.019150,512.0,2.307909,...,0.099472,0.097672,0.097511,0.098576,0.100304,0.101106,0.101240,56.066785,2420.182924,3.739992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4045,ccs97.csv,20,1024,512,isa,10.095220,0.028078,0.019717,512.0,1.809512,...,0.099225,0.098155,0.098863,0.098917,0.099607,0.101045,0.100253,61.413367,2956.668581,3.693637
4046,ccs97.csv,21,1024,512,isa,13.191001,0.035397,0.025764,512.0,1.805456,...,0.099974,0.099768,0.099368,0.098987,0.099178,0.100506,0.100195,59.157672,2680.915698,3.684214
4047,ccs97.csv,22,1024,512,isa,15.309671,0.040282,0.029902,512.0,1.803122,...,0.099833,0.098662,0.099882,0.099455,0.100108,0.099775,0.099818,53.887326,2396.451854,3.721072
4048,ccs97.csv,23,1024,512,isa,16.876747,0.056152,0.032962,512.0,1.804665,...,0.101097,0.098816,0.098541,0.099515,0.099653,0.099725,0.099829,45.835197,1638.623121,3.751509


In [13]:
columns_to_drop = ['value__sum_values', 'value__variance', 'value__length']

# Drop columns from each DataFrame
df_features_a = df_features_a.drop(columns=columns_to_drop, errors='ignore')
df_features_b = df_features_b.drop(columns=columns_to_drop, errors='ignore')
df_features_c = df_features_c.drop(columns=columns_to_drop, errors='ignore')

print("Dropped specified columns from df_features_a, df_features_b, and df_features_c.")
print(f"New shape of df_features_a: {df_features_a.shape}")
print(f"New shape of df_features_b: {df_features_b.shape}")
print(f"New shape of df_features_c: {df_features_c.shape}")

Dropped specified columns from df_features_a, df_features_b, and df_features_c.
New shape of df_features_a: (4050, 46)
New shape of df_features_b: (4050, 46)
New shape of df_features_c: (4050, 46)


In [14]:
feature_columns = [col for col in df_features_a.columns if not col in ['file_name', 'window_num', 'window_size', 'overlap', 'signal_type']]

feature_rename_map = {
    old_name: f'tsff_{i+1}'
    for i, old_name in enumerate(feature_columns)
}

def rename_df_features(df: pd.DataFrame, phase_suffix: str):
    """Rename feature columns as tsff_<phase>_<number>."""
    df_renamed = df.copy()

    new_columns = {}

    for col in df_renamed.columns:
        if col in feature_rename_map:
            feature_num = feature_rename_map[col].replace('tsff_', '')
            new_columns[col] = f"tsff_{phase_suffix}_{feature_num}"
        else:
            new_columns[col] = col

    return df_renamed.rename(columns=new_columns)

# Apply the renaming to each phase dataframe
df_features_a_renamed = rename_df_features(df_features_a, '_a')
df_features_b_renamed = rename_df_features(df_features_b, '_b')
df_features_c_renamed = rename_df_features(df_features_c, '_c')


In [15]:
df_features_a_renamed

,file_name,window_num,window_size,overlap,signal_type,tsff__a_1,tsff__a_2,tsff__a_3,tsff__a_4,tsff__a_5,...,tsff__a_32,tsff__a_33,tsff__a_34,tsff__a_35,tsff__a_36,tsff__a_37,tsff__a_38,tsff__a_39,tsff__a_40,tsff__a_41
0,ccs0.csv,0,1024,512,isa,0.006100,-0.002417,2.301300,2.301301,3.31785,...,0.101323,0.101909,0.100975,0.099336,0.098091,0.098492,0.099865,44.531847,1359.664937,3.726162
1,ccs0.csv,1,1024,512,isa,0.006102,0.000287,2.304617,2.304617,3.31785,...,0.099752,0.100891,0.101756,0.100928,0.098892,0.098178,0.097782,50.569366,1915.515404,3.725282
2,ccs0.csv,2,1024,512,isa,0.006105,0.005631,2.308459,2.308466,3.32275,...,0.097817,0.098952,0.100346,0.101478,0.100874,0.099057,0.097575,57.884691,2630.521291,3.723227
3,ccs0.csv,3,1024,512,isa,0.008545,0.012407,2.310324,2.310358,3.32275,...,0.097653,0.097192,0.098835,0.099970,0.101012,0.101001,0.098956,59.580490,2656.316965,3.723227
4,ccs0.csv,4,1024,512,isa,0.013427,0.019150,2.307909,2.307988,3.31300,...,0.099472,0.097672,0.097511,0.098576,0.100304,0.101106,0.101240,56.066785,2420.182924,3.739992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4045,ccs97.csv,20,1024,512,isa,0.028078,0.019717,1.809512,1.809619,2.72945,...,0.099225,0.098155,0.098863,0.098917,0.099607,0.101045,0.100253,61.413367,2956.668581,3.693637
4046,ccs97.csv,21,1024,512,isa,0.035397,0.025764,1.805456,1.805640,2.72945,...,0.099974,0.099768,0.099368,0.098987,0.099178,0.100506,0.100195,59.157672,2680.915698,3.684214
4047,ccs97.csv,22,1024,512,isa,0.040282,0.029902,1.803122,1.803370,2.70995,...,0.099833,0.098662,0.099882,0.099455,0.100108,0.099775,0.099818,53.887326,2396.451854,3.721072
4048,ccs97.csv,23,1024,512,isa,0.056152,0.032962,1.804665,1.804966,2.73435,...,0.101097,0.098816,0.098541,0.099515,0.099653,0.099725,0.099829,45.835197,1638.623121,3.751509


In [16]:
# Define common columns for merging (metadata that should be the same across phases for a given window)
common_merge_cols = ['file_name', 'window_num', 'window_size', 'overlap']

# Start with phase A features, selecting only the necessary columns
df_merged = df_features_a_renamed[common_merge_cols + [col for col in df_features_a_renamed.columns if col.startswith('tsff_')]]

# Merge with phase B features
# Select only the features and common merge columns from df_features_b_renamed
df_b_for_merge = df_features_b_renamed[common_merge_cols + [col for col in df_features_b_renamed.columns if col.startswith('tsff_')]]
df_merged = pd.merge(df_merged, df_b_for_merge, on=common_merge_cols, how='inner')

# Merge with phase C features
# Select only the features and common merge columns from df_features_c_renamed
df_c_for_merge = df_features_c_renamed[common_merge_cols + [col for col in df_features_c_renamed.columns if col.startswith('tsff_')]]
df_merged = pd.merge(df_merged, df_c_for_merge, on=common_merge_cols, how='inner')

print(f"Merged DataFrame created with {len(df_merged)} rows and {df_merged.shape[1]} columns.")
display(df_merged.head())

Merged DataFrame created with 4050 rows and 127 columns.


,file_name,window_num,window_size,overlap,tsff__a_1,tsff__a_2,tsff__a_3,tsff__a_4,tsff__a_5,tsff__a_6,...,tsff__c_32,tsff__c_33,tsff__c_34,tsff__c_35,tsff__c_36,tsff__c_37,tsff__c_38,tsff__c_39,tsff__c_40,tsff__c_41
0,ccs0.csv,0,1024,512,0.006100,-0.002417,2.301300,2.301301,3.31785,3.31785,...,0.097479,0.098650,0.100175,0.101384,0.100958,0.099093,0.097982,58.740649,2699.208433,3.720837
1,ccs0.csv,1,1024,512,0.006102,0.000287,2.304617,2.304617,3.31785,3.31785,...,0.097568,0.097446,0.098501,0.099806,0.100994,0.101235,0.099277,59.639199,2635.586419,3.721277
2,ccs0.csv,2,1024,512,0.006105,0.005631,2.308459,2.308466,3.32275,3.32275,...,0.099768,0.097977,0.097417,0.098573,0.099946,0.100945,0.101464,55.919723,2412.955318,3.723445
3,ccs0.csv,3,1024,512,0.008545,0.012407,2.310324,2.310358,3.32275,3.32275,...,0.101659,0.100370,0.098641,0.097871,0.098542,0.100370,0.101277,49.270435,1952.779603,3.726119
4,ccs0.csv,4,1024,512,0.013427,0.019150,2.307909,2.307988,3.31300,3.31300,...,0.101695,0.101945,0.100551,0.099040,0.098222,0.098446,0.099972,44.254525,1350.726906,3.726162


In [17]:
## ----- CREATING SOME DICTIONARIES TO MAP THE FILE NAMES, GROUPS AND LABELS (TARGET) ----##

motor_conditions_ranges = {
    "healthy_low": range(0, 18), # 18
    "one_broken_low": range(60, 68), # 8
    "two_broken_low": range(120, 128), # 8

    "healthy_med": range(20, 38),#18
    "one_broken_med": range(80, 98),#18
    "two_broken_med": range(140, 148), #8

    "healthy_high": range(40, 58), #18
    "one_broken_high": range(100, 118), #18
    "two_broken_high": range(160, 178) #18
}

def generate_valid_files_list(motor_conditions_ranges: dict) -> list:
  """
  Generates a list of valid file names based on motor condition ranges.

  Args:
    motor_conditions_ranges (dict): A dictionary where keys are condition names
                                     and values are range objects representing file indices.

  Returns:
    list: A list of file names (e.g., ['ccs0.csv', 'ccs1.csv', ...]).
  """
  valid_files = []
  for r in motor_conditions_ranges.values():
      for i in r:
          valid_files.append(f"ccs{i}.csv")
  return valid_files

def generate_file_to_class_map(motor_conditions_ranges: dict) -> dict:
  """
  Generates a mapping from file names to their corresponding class labels.

  Args:
    motor_conditions_ranges (dict): A dictionary where keys are condition names
                                     and values are range objects representing file indices.

  Returns:
    dict: A dictionary where keys are file names (e.g., 'ccs0.csv') and values
          are class labels (1 for healthy, 2 for one broken, 3 for two broken).
  """
  file_to_class_map = {}

  # Class 1: Healthy conditions
  for key in ["healthy_low", "healthy_med", "healthy_high"]:
      for i in motor_conditions_ranges[key]:
          file_to_class_map[f"ccs{i}.csv"] = 1

  # Class 2: One broken condition
  for key in ["one_broken_low", "one_broken_med", "one_broken_high"]:
      for i in motor_conditions_ranges[key]:
          file_to_class_map[f"ccs{i}.csv"] = 2

  # Class 3: Two broken conditions
  for key in ["two_broken_low", "two_broken_med", "two_broken_high"]:
      for i in motor_conditions_ranges[key]:
          file_to_class_map[f"ccs{i}.csv"] = 3

  return file_to_class_map


def generate_file_to_group_map(motor_conditions_ranges: dict) -> dict:
  """
  Generates a mapping from file names to their corresponding group names.

  Args:
    motor_conditions_ranges (dict): A dictionary where keys are group names
                                     and values are range objects representing file indices.

  Returns:
    dict: A dictionary where keys are file names (e.g., 'ccs0.csv') and values
          are group names (e.g., 'healthy_low').
  """
  file_to_group_map = {}
  for group_name, file_range in motor_conditions_ranges.items():
    for i in file_range:
        file_to_group_map[f"ccs{i}.csv"] = group_name

  return file_to_group_map

valid_files = generate_valid_files_list(motor_conditions_ranges)
file_to_class_map = generate_file_to_class_map(motor_conditions_ranges)
file_to_group_map = generate_file_to_group_map(motor_conditions_ranges)

In [18]:
# Filtering df_merged for only those embeddings that belong to valid files
df_merged_valid = df_merged[df_merged['file_name'].isin(valid_files)].copy()
print(f"Generated {len(valid_files)} valid files:")


# Attaching target column
df_merged_valid['class'] = df_merged_valid['file_name'].map(file_to_class_map)

# Add a file group column to enable stratified splitting
df_merged_valid['file_group'] = df_merged_valid['file_name'].map(file_to_group_map)
display(df_merged_valid.head())

Generated 132 valid files:


,file_name,window_num,window_size,overlap,tsff__a_1,tsff__a_2,tsff__a_3,tsff__a_4,tsff__a_5,tsff__a_6,...,tsff__c_34,tsff__c_35,tsff__c_36,tsff__c_37,tsff__c_38,tsff__c_39,tsff__c_40,tsff__c_41,class,file_group
0,ccs0.csv,0,1024,512,0.006100,-0.002417,2.301300,2.301301,3.31785,3.31785,...,0.100175,0.101384,0.100958,0.099093,0.097982,58.740649,2699.208433,3.720837,1,healthy_low
1,ccs0.csv,1,1024,512,0.006102,0.000287,2.304617,2.304617,3.31785,3.31785,...,0.098501,0.099806,0.100994,0.101235,0.099277,59.639199,2635.586419,3.721277,1,healthy_low
2,ccs0.csv,2,1024,512,0.006105,0.005631,2.308459,2.308466,3.32275,3.32275,...,0.097417,0.098573,0.099946,0.100945,0.101464,55.919723,2412.955318,3.723445,1,healthy_low
3,ccs0.csv,3,1024,512,0.008545,0.012407,2.310324,2.310358,3.32275,3.32275,...,0.098641,0.097871,0.098542,0.100370,0.101277,49.270435,1952.779603,3.726119,1,healthy_low
4,ccs0.csv,4,1024,512,0.013427,0.019150,2.307909,2.307988,3.31300,3.31300,...,0.100551,0.099040,0.098222,0.098446,0.099972,44.254525,1350.726906,3.726162,1,healthy_low


In [19]:
# ---- Train-test split at file-level while stratifying on file_group ---- #
file_df = df_merged_valid[['file_name', 'file_group']].drop_duplicates()

from sklearn.model_selection import train_test_split
train_files, test_files = train_test_split(file_df["file_name"],
                                           stratify=file_df["file_group"],
                                           test_size=0.2,
                                           random_state=67)

train_df = df_merged_valid[df_merged_valid["file_name"].isin(train_files)]
test_df = df_merged_valid[df_merged_valid["file_name"].isin(test_files)]

In [20]:
# Checking this worked.  Should give an empty set
set(train_df["file_name"]) & set(test_df["file_name"])

set()

In [21]:
print(train_df["file_group"].value_counts(normalize=True))
print(test_df["file_group"].value_counts(normalize=True))

file_group
healthy_low        0.133333
one_broken_high    0.133333
two_broken_high    0.133333
healthy_med        0.133333
healthy_high       0.133333
one_broken_med     0.133333
two_broken_low     0.066667
two_broken_med     0.066667
one_broken_low     0.066667
Name: proportion, dtype: float64
file_group
healthy_low        0.148148
one_broken_high    0.148148
two_broken_high    0.148148
healthy_med        0.148148
healthy_high       0.148148
one_broken_med     0.148148
two_broken_low     0.037037
two_broken_med     0.037037
one_broken_low     0.037037
Name: proportion, dtype: float64


In [22]:
from sklearn.preprocessing import StandardScaler

# Identify feature columns (those starting with 'moment_')
feature_cols = [col for col in train_df.columns if col.startswith('tsff_')]

# Prepare training data
X_train = train_df[feature_cols]
y_train = train_df['class']

# Prepare testing data
X_test = test_df[feature_cols]
y_test = test_df['class']

# Initialize StandardScaler
scaler = StandardScaler()

# Fit on training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data standardized using StandardScaler.")

Data standardized using StandardScaler.


In [23]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np # Import numpy for type hinting np.ndarray
from sklearn.linear_model import LogisticRegression

def train_svc_model(X_train: pd.DataFrame | np.ndarray, y_train: pd.Series, kernel: str = 'rbf', class_weight: str = 'balanced', random_state: int = 42) -> SVC:
  """
  Trains an SVC classifier and returns the trained model.

  Args:
    X_train (pd.DataFrame | np.ndarray): Training features.
    y_train (pd.Series): Training labels.
    kernel (str): Specifies the kernel type to be used in the algorithm.
    class_weight (str): Weights associated with classes.
    random_state (int): The seed of the pseudo random number generator.

  Returns:
    SVC: The trained SVC model.
  """
  model = SVC(kernel=kernel, class_weight=class_weight, random_state=random_state)
  print(f"Training SVM model with {kernel} kernel and balanced class weights...")
  model.fit(X_train, y_train)
  print(f"SVM model training complete with {kernel} kernel.")
  return model

def evaluate_model(y_true: pd.Series, y_pred: np.ndarray, title: str):
  """
  Evaluates a classification model by printing the classification report and confusion matrix.

  Args:
    y_true (pd.Series): True labels.
    y_pred (np.ndarray): Predicted labels.
    title (str): Title for the evaluation output.
  """
  print(f"\nClassification Report ({title}):")
  print(classification_report(y_true, y_pred))
  print(f"\nConfusion Matrix ({title}):")
  print(confusion_matrix(y_true, y_pred))

def train_log_reg_model(X_train: pd.DataFrame | np.ndarray, y_train: pd.Series,
                      solver: str = 'liblinear', penalty: str = 'l2', C: float = 1.0,
                      class_weight: str = 'balanced', random_state: int = 42, max_iter: int = 1000) -> LogisticRegression:
  """
  Trains a Logistic Regression classifier and returns the trained model.

  Args:
    X_train (pd.DataFrame | np.ndarray): Training features.
    y_train (pd.Series): Training labels.
    solver (str): Algorithm to use in the optimization problem.
    penalty (str): Used to specify the norm of the penalty.
    C (float): Inverse of regularization strength.
    class_weight (str): Weights associated with classes.
    random_state (int): The seed of the pseudo random number generator.
    max_iter (int): Maximum number of iterations for the solver to converge.

  Returns:
    LogisticRegression: The trained Logistic Regression model.
  """
  model = LogisticRegression(solver=solver, penalty=penalty, C=C,
                             class_weight=class_weight, random_state=random_state, max_iter=max_iter)
  print(f"Training Logistic Regression model with solver='{solver}', penalty='{penalty}', C={C} and balanced class weights...")
  model.fit(X_train, y_train)
  print("Logistic Regression model training complete.")
  return model

In [24]:
# Train SVM model with RBF kernel on UNscaled data
svm_model_unscaled_rbf = train_svc_model(X_train, y_train, kernel='rbf')

Training SVM model with rbf kernel and balanced class weights...
SVM model training complete with rbf kernel.


In [25]:
# Make predictions on the unscaled test set
y_pred_unscaled_rbf = svm_model_unscaled_rbf.predict(X_test)

# Evaluate the model
evaluate_model(y_test, y_pred_unscaled_rbf, "RBF Kernel SVM on Unscaled Data")


Classification Report (RBF Kernel SVM on Unscaled Data):
              precision    recall  f1-score   support

           1       0.71      0.68      0.69       300
           2       0.83      0.75      0.79       225
           3       0.60      0.74      0.66       150

    accuracy                           0.71       675
   macro avg       0.71      0.72      0.71       675
weighted avg       0.72      0.71      0.72       675


Confusion Matrix (RBF Kernel SVM on Unscaled Data):
[[203  32  65]
 [ 47 168  10]
 [ 36   3 111]]


In [26]:
# Train SVM model with RBF kernel on scaled data
svm_model_scaled_rbf = train_svc_model(X_train_scaled, y_train, kernel='rbf')

Training SVM model with rbf kernel and balanced class weights...
SVM model training complete with rbf kernel.


In [27]:
# Make predictions on the scaled test set
y_pred_scaled_rbf = svm_model_scaled_rbf.predict(X_test_scaled)

# Evaluate the model
evaluate_model(y_test, y_pred_scaled_rbf, "RBF Kernel SVM on Scaled Data")


Classification Report (RBF Kernel SVM on Scaled Data):
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       300
           2       1.00      1.00      1.00       225
           3       1.00      1.00      1.00       150

    accuracy                           1.00       675
   macro avg       1.00      1.00      1.00       675
weighted avg       1.00      1.00      1.00       675


Confusion Matrix (RBF Kernel SVM on Scaled Data):
[[300   0   0]
 [  0 225   0]
 [  0   0 150]]
